### ISSUE TITLE
Infinite loop initializing score reels

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf#1009]
If there is no power to the rotate score reels (e.g. fuse blown) it will go into an infinite loop trying to zero them.

**Comment by jabdoa2** [comment]
I guess this is "bug compatibility" with older EMs, right? We can probably add a timeout to give up after certain time.

I started refactoring the scorereels in  #825 a while back. However, it need testing on real hardware since I don't own any physical reels. Would you like to test the code? I don't want to change the old code because it is quite messy.

**Comment by jabdoa2** [comment]
fixed in new code
