### ISSUE TITLE
Update ruamel

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1026]
We pin ruamel to version 0.10.x. Currently, 0.11+ does not work. Find out why and fix it.

**Comment by qcapen** [comment]
I believe ruamel.yaml is pinned to 0.10.x due to 0.11.x+ loads all yaml documents as YAML 1.2 spec documents by default (and not YAML 1.1 which MPF relies on for several things at the moment).  It appears we should be able to set the YAML spec in code and update the ruamel.yaml version.  Also, ruamel.yaml is undergoing a major breaking API change in 0.15.x and recommends all production software be pinned to <0.15.

See [http://yaml.readthedocs.io/en/stable/detail.html#document-version-support](http://yaml.readthedocs.io/en/stable/detail.html#document-version-support) for more information.

**Comment by jabdoa2** [comment]
I played around with it a few weeks ago and the changes looked more than trivial. Dunno if it is worth the effort currently
