### ISSUE TITLE
Control_events in counters

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1180]
Increase by two/decrease etc

**Comment by kirakrishnan** [comment]
Hi jabdoa2, can I work on this.?

**Comment by jabdoa2** [comment]
Yes you can. Start by setting up MPF in dev mode: http://docs.missionpinball.org/en/dev/about/contributing_to_mpf.html. Let me know if you got any questions. We will help you to find the right places to make that change.

**Comment by kirakrishnan** [comment]
Hi @jabdoa2 . I have followed the steps and installed mpf and mpf-mc. I am able to see version when I do mpf --version. Please tell me what to do next

**Comment by jabdoa2** [comment]
Awesome! The issue is about adding control events to the Counter class here: https://github.com/missionpinball/mpf/blob/dev/mpf/devices/logic_blocks.py#L266. 

Those should work similar to timer control_events: http://docs.missionpinball.org/en/dev/config/timers.html#control-events. Those are defined here https://github.com/missionpinball/mpf/blob/dev/mpf/config_spec.yaml#L1401 and implemented here: https://github.com/missionpinball/mpf/blob/dev/mpf/devices/timer.py#L145.

The idea is to add a ``control_events`` entry to counters in config_spec which will allow those entries in config. You can then add a test for it here: https://github.com/missionpinball/mpf/blob/dev/mpf/tests/test_LogicBlocks.py and put the config for it in a mode: https://github.com/missionpinball/mpf/blob/dev/mpf/tests/machine_files/logic_blocks/modes/mode1/config/mode1.yaml. Then go and implement some logic inside the counter (similar to the timer). I guess the first action would be to decrement the counter (first by one, then by an arbitrary amount). Then the same for incrementing and setting the value.

**Comment by jonroby2** [comment]
Hi! is this still an issue? I'm looking through the code and trying to figure out how this all connects together.

**Comment by jabdoa2** [comment]
Hi jonroby2,

This is still open. Feel free to ask any questions! Either here or in our forum https://groups.google.com/forum/#!forum/mpf-users

Jan

**Comment by jonroby2** [comment]
Hi

Been working on this and I have a question - how does the increment/decrement value get passed to the counter? is it passed as a parameter with the event or is it set as an event and then the incement/decrement events use that value?

**Comment by avanwinkle** [comment]
Hey @jonroby2-

Since the counter currently stores a hard-coded `hit_value` property that's set once during initialization by the config `count_interval`, I think the more direct approach would be to post a hit value with the event. With this, the hit event handler could read the event for a value and use that instead of `self.hit_value`. 

Creating an event to _change_ `self.hit_value` would require a new handler for the Counter and new behavior to change `self.hit_value` (and probably other behavior to restore the default). I'm not saying that it'd be a huge burden to do, but if there's no compelling argument for/against either implementation from a game design standpoint, might as well take the simpler approach (in my opinion).

And thinking about game design... I feel like it would be safer to pass the hit value with the event. Otherwise one mode might change it and another mode wouldn't know, and it might get difficult to track down why the counts aren't as expected.

Thanks for jumping into the MPF development party!
