### ISSUE TITLE
Virtual locks double-counting balls

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1373]
#1350 changed the way balls are counted in locks, which introduced a bug where virtual locks would double-count entrances.

Specifically, [Line 228](https://github.com/missionpinball/mpf/pull/1350/files#diff-48f48b71b010d05b177976babd8dcb75R228) defines `new_locked_balls` as the incremented value and [Line 240](https://github.com/missionpinball/mpf/pull/1350/files#diff-48f48b71b010d05b177976babd8dcb75R240) sets the `self.locked_balls` to that incremented value.

[Line 274](https://github.com/missionpinball/mpf/pull/1350/files#diff-48f48b71b010d05b177976babd8dcb75R274) evaluates the remaining space against the new incremented value—but `self.remaining_virtual_space_in_lock` is calculated based on `self.locked_balls`, which was _already incremented_ in line 240.

No tests caught this bug because line 274 considers the lock "full" if the remaining space minus incremented value is less than _but not equal to_ zero, so a 2-ball multiball lock will not be full on ball one (`1 - 1`) and less than zero on ball two (`0 - 2 `)... so the result is as expected despite the mathematical error. However, a 3-ball lock does expose the bug, not on ball one (`2 - 1`), but on ball two (`1 - 2`) which falsely reports itself as full.

I have drafted a fix to the bug, which uses `self.remaining_virtual_space_in_lock` to determine fullness—which provides the correct value, because the `self.locked_balls` has already incremented. For `"physical-only"` locks, the physically-remaining space is used. I have also written a suite of tests for 2-ball and 3-ball locks to verify correct counting. 

To avoid conflicts with #1372 I have based these changes on that branch, which is only on my fork so I can't make a PR yet. The diff is currently visible here: https://github.com/avanwinkle/mpf/compare/bugfix-device-placeholders...avanwinkle:bugfix-multiball-doublecounting

**Comment by jabdoa2** [comment]
More tests in this area are welcome! Four different locking and counting strategies, unfortunately, come with a lot of edge cases. I tried to reduce complexity in that change. Ideally counting would be the same for all strategies. I guess the or condition has to be there because `remaining_virtual_space_in_lock` is not valid for `physical_only`. So yeah looks good to me!

In your test you could use the `test_config` decorator (https://github.com/missionpinball/mpf/blob/dev/mpf/tests/MpfTestCase.py#L31) to make it cleaner. Besides that it looks very good.

**Comment by jabdoa2** [comment]
Fixed by https://github.com/missionpinball/mpf/pull/1377
