### ISSUE TITLE
Time of day as placeholder

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1402]
Implement seconds, minutes, hours, day, month and year as placeholder. This can be useful in conditions (i.e. midnight multiball).

**Comment by jabdoa2** [comment]
https://groups.google.com/forum/m/#!topic/mpf-users/opVE1U62ggU

**Comment by pmansukhani** [comment]
I'd like to take this up, but I need some more clarity on what we're trying to achieve. Or another example that achieves something similar. Thanks.

**Comment by jabdoa2** [comment]
Hi @pmansukhani sorry I missed your comment. You sure can. The idea is to add a placeholder into machine like `machine.date.minute` or `machine.date.hour` which return the minutes or hour of the day. Those placeholder should then work like any other placeholders (http://docs.missionpinball.org/en/dev/config/instructions/dynamic_values.html). 

For instance this should work:

```
event_player:
  game_started{machine.date.minute == 0 and machine.date.hour=0}: start_midnight_multiball
```

When a game is started at midnight `start_midnight_multiball` should be posted which then can trigger an easteregg multiball.

**Comment by filipe-gomes** [comment]
I would like to take a crack at this, if it's still up for grabs.

**Comment by jabdoa2** [comment]
Go for it!

**Comment by atummons** [comment]
@filipe-gomes Are you doing anything with this one anymore?  

@jabdoa2 Does this need an interface in settings to allow the user to enter the time, and then the system takes over counting?  Or does this just need to read the system clock, and convert if from date time into machine variables for YYYY-MM-DD HH:MM:SS (each as its own machine variable)?

**Comment by filipe-gomes** [comment]
@atummons you can take it. I'd completely forgotten about this, and really just don't have the time anymore

**Comment by jabdoa2** [comment]
> @jabdoa2 Does this need an interface in settings to allow the user to enter the time, and then the system takes over counting? Or does this just need to read the system clock, and convert if from date time into machine variables for YYYY-MM-DD HH:MM:SS (each as its own machine variable)?

This would use the current time of day of the machine. Guess we need to add an option to change that in service mode later or it will certainly be incorrect in most machines.

**Comment by atummons** [comment]
@jabdoa2 How do you best want this to work?  As of now, I have the machine vars created for Year, Month, Day, Hour, Minute, Second.  And test to verify it matches the machine time.  This is working.

However, I don't think it updates.  I think it is loading once and then staying at that value, instead of updating.  I don't want to overload the system, but it really should be in a loop that updates every second to grab the new datetime value from the machine.  Or is there a different way that you would want it done to be less intensive.  I wouldn't log it, but It needs to constantly be telling the machine what time it is now, not the time when the machine started.  If this is already tracked elsewhere, I could tap off of that.

Thanks!

**Comment by atummons** [comment]
PR #1566 covers this item.

**Comment by atummons** [comment]
@jabdoa2 This can be closed now.

**Comment by jabdoa2** [comment]
Thanks @atummons
