### ISSUE TITLE
Extra ball handling in Game

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#257]
We got some untested extra ball handling in the Game mode. Currently this feature is very much like a ball save. Should we remove it?

However, we still need a real extra ball features. That ball should be given after the last ball of the player. So we got a few options here:
a) Implement extra ball in Game. How is it enabled?
b) Implement extra ball as new device
c) Extend ball_save. Add an option 'award_at_last_ball' or similar

What do you think?

**Comment by toomanybrians** [comment]
I like the way EB works now. I don’t think it needs to be a device since it’s simple, and everything else it does is part of the game mode (logic to know which player is up, when to switch players, current ball count, etc)

So really we probably just need to add an event “request_extra_ball” which actually awards it?

That can call the method to add it, which would just check to make sure extra balls are enabled, that the max EBs per ball have not been exceeded, and that max EBs per game have not been exceeded. Then if it awards it, it posts “extra_ball_awarded” which is what people can use to do their shows and stuff.
