### ISSUE TITLE
Attract Mode shows not stopping - showing between balls

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf#344]
From attract.yaml file:  

show_player:
  mode_attract_started:
    attract_dmd_loop:
      action: play
      loops: -1
      speed: 1

  mode_attract_stopping:
    attract_dmd_loop:
      action: stop
      hold: false

attract_dmd_loop show is stuck on the last slide that was shown when game was started.
Eg.  slide is visible between bonus_count mode and next ball.

**Comment by toomanybrians** [comment]
Log file:

[2016-06-02-18-30-25-mpf-DESKTOP-B0OAM7V.txt](https://github.com/missionpinball/mpf/files/296657/2016-06-02-18-30-25-mpf-DESKTOP-B0OAM7V.txt)

**Comment by toomanybrians** [comment]
This is a key issue. show_player.play() with action stop runs, clear event is posted, but clear is posted with 'attract' as the key, but I think the attract show will have the original show name plus the ID as the key, so the slide isn't getting cleared.

Dunno the fix. We talked about changing keys to lists, so we could have the mode and the show name as keys. Or we make sure the show_player call to clear uses the right key name? Actually, yeah, why's that posting with the mode name as the key and not the show name??

**Comment by toomanybrians** [comment]
show_player.play() gets the mode as the key since it's in the mode's config. That means the mode name is passed as the key to RunningShow. But.. that doesn't make sense, because then it should be the right key to kill it later.

Test plan is to track the key as it goes through show_player.play(), Show.play(), RunningShow.play(), etc. to see what key actually ends up in there, then to verify the key that's passed with 'clear'

**Comment by jabdoa2** [comment]
@MarkInc666 can you test the https://github.com/missionpinball/mpf/tree/show_refactoring branch? this should be fixed there.

**Comment by MarkInc666** [comment]
Jan,  I can give it a try - but how do I test this branch?
I have mpf/mpf-mc installed through pip in my python34/lib/site-packages/ folder
Where do I place the show_refactoring zip files?
