### ISSUE TITLE
Ball Search should block shots and/or scoring?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#522]
Currently when ball search is running, it's possible to advance shots or score things when devices that hit switches execute their searches. We should probably go through the devices and make sure they disable or something during ball search? Like with shots, maybe?

Dunno... this is sort of a placeholder of something we need to investigate. Maybe it's not a problem.

**Comment by jabdoa2** [comment]
Any shot hit would instantly disable ball search. So that would be fine, right?

**Comment by toomanybrians** [comment]
I think that's the bug, though? Like if ball search on a drop target happens and it fires the knockdown coil, that would make MPF think that the ball was found?

**Comment by jabdoa2** [comment]
If that switch has the playfield tag thats what will happen. If not there is no way for MPF to know that this switch is on that playfield.

In the special case of drop targets, its hard to know because when ball search resets or knocks them down it will change the switch itself. We can improve the ball_search logic in the drop_taget. Is this about drop targets or general?
