### ISSUE TITLE
set_machine_var vs create_machine_var

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#718]
Can we remove create_machine_var? What is the usecase for set_machine_var which just ignores variables when they have not been created before.

I propose either:
a) Remove create_machine_var
or:
b) Raise an exception when using set_machine_var (MPF will no longer start in almost all cases)

**Comment by toomanybrians** [comment]
Let's change machine vars so they are more similar to player vars. We can use the same base class and they can live in self.machine.vars. That way you don't need the create method.

Then for machine vars that persist to disk, we can create another subclass and only those will use the create method (since they need to have settings for expire time, etc.)
