### ISSUE TITLE
Add temp disable to autofire devices if they fire too fast/long (anti machine-gunning)

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#777]
Autofire coils (and related devices based on autofires like in #636 like slingshots, pop bumpers, etc) should have a config option that will temporarily disable them if they fire too fast or too long. A config option could be something like "if it fires X times in Y secs then disable it for Z secs".

Since autofires are handled in hw rules, we'd have to watch for switch events which come on while the autofire is active and then temporarily disable the autofire.

**Comment by jabdoa2** [comment]
We got that. I think it is called recycle time. Not all platforms support it though

**Comment by toomanybrians** [comment]
I'm thinking this feature though can go longer than the 255ms that the platform(s) support. For example, in WoZ, it's possible that a ball can get "stuck" in the upper slingshot area for too long and not come down. So this setting would be more like "if this slingshot fires more than 10 times in 10 seconds, disable it for 5 secs so the ball will come down and the game will continue".

**Comment by toomanybrians** [comment]
this is a real setting from woz btw, though I forget exactly how they phrase it

**Comment by jabdoa2** [comment]
Makes sense. With the next platform refactoring we will probably support longer recycle ms in software but this will not help here because it actually counts the hits.

**Comment by Aiden166** [comment]
Is this still open? I think I might know how to do it but I'll need to explore the codebase some more to figure out the specifics, such as where I would even put it.

**Comment by jabdoa2** [comment]
Hi Aiden,

Yes this is still open. Let me know if you have any questions. 


Jan

**Comment by Aiden166** [comment]
Okay. I'll get on this then. Thanks for responding so quickly!

**Comment by Aiden166** [comment]
I'm sorry. This is much more complicated than I thought it would be. I will keep working on it, but it will probably take me a while.

**Comment by Aiden166** [comment]
I think I've figured out how to do it, but I have two questions. One, is _hit method inside of the AutofireCoil class called whenever the device each instance represents activated, and two, would it be better to edit the class itself rather than use events? It seems to me that would be the better option as that way you don't have to deal with a separate event for each instance.

**Comment by Aiden166** [comment]
@jabdoa2  Submitted a pull request. I'd be very grateful if you could review it. I am currently unable to perform any tests due to the limitations of the laptop I'm currently using, so this is completely untested. Also, know me, I probably did something incredibly stupid and broke the whole build. So, sorry.

**Comment by Aiden166** [comment]
Yeah, I screwed up, it seems. Didn't even realize there were automated tests like this.
