### ISSUE TITLE
Ball auto-launched from plunger lane

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#778]
Hit start, ball ejected from trough and auto-launched from plunger. It should wait for the player to plunge.

This is using @jabdoa2 manual_plunger_crash branch, but I think I've seen this happen before. 

Update: This happens pretty frequently now. When it does, the game gets kind of confused. 
When I flipped back to dev instead of your build, this went away.

Log file attached.
[2017-02-16-23-30-11-mpf-DESKTOP-QBFID3T.log.zip](https://github.com/missionpinball/mpf/files/782389/2017-02-16-23-30-11-mpf-DESKTOP-QBFID3T.log.zip)

**Comment by jabdoa2** [comment]
From the log the problem seems to be that MPF thinks that be ball skipped the launcher (got plunged without hitting the plunger switch) and then fell back into the launcher. Therefore, the launcher will autolaunch the ball.  The reason MPF considers the ball to have skipped the launcher is that a playfield switch is hit directly after the eject of the trough (s_droptarget5).

I see a few possible paths to resolve this issue:
1. Short term: Remove the "playfield_active" tag from the drop target switches
2. Find a way to no trigger the playfield as active when resetting drop targets (Issue #784, more specific version of #779)
3. Enforce a minimum time until the ball can be confirmed in the skip case (Issue #785)
