### ISSUE TITLE
Explore updating MPF to asynchronous logging

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#811]
Our logging is based on the Python 2.7 way of doing things, and in Python 3.2 they introduced a feature called asynchronous logging via the QueueListener class. It won't block threads like the old way. 

Switching to this may prevent the lag associated with tons of events coming in when event logging is set to full. It's also possible that it could help things work on Windows a little better, but that might be wishful thinking.

More info: http://plumberjack.blogspot.co.uk/2010/09/improved-queuehandler-queuelistener.html

From python.org: https://docs.python.org/3.4/library/logging.handlers.html#queuehandler
and https://docs.python.org/3.4/library/logging.handlers.html#queuelistener

I don't think this is needed for 0.33, unless you think it's easy.

**Comment by jabdoa2** [comment]
Should be easy. @toomanybrians already implemented most requirements for that

**Comment by toomanybrians** [comment]
Oh wow. Nice find!

Yeah this should be easy because now MPF has a central logging module which is used for all logging instead of having individual logging calls scattered throughout. So changing to this will only need to be done in that one location and should be easy. (I say that having not clicked the links yet explaining it.) But as a concept, should be straightforward.
