### ISSUE TITLE
Add options to multiballs to support TOTAN style unlimited multiball

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#815]
After going through scenarios of how to enable the "unlimited balls for 30 seconds" kind of multiball (TOTAN, WCS, CV...) it appears to make more sense to build this into MPF than to try to rig something with other features. If we extend multiballs with a few params, we can make this easy to do.

We need to add something like "drain_all_on_stop: (True/False)" and "resume_single_ball_events" to the config. resume_single_ball_events can be the multiball's stop_event by default (so it drains the balls, then kicks out one right away), or it can be used to do something in between draining all the balls and resuming, like to play a show that kicks off an event at the end that ejects a ball to the plunger lane to continue playing.

The act of draining all the balls should include disabling flippers and autofires, though it can post an event that we can hook elsewhere to disable other things as needed.

**Comment by jabdoa2** [comment]
Hard to do generically. What we currently can do is to add a multiball and add a ball save with delay on when the mb stops. That could become build in. Disabling autofires and flippers however will not work automatically. You have to add events there

**Comment by toomanybrians** [comment]
At first I thought you could disable the multiball and flippers, and at the same time enable a regular ball save to save one ball. The problem is that would serve the saved ball right away while the other balls were still draining. So I figured we had to do this in code, and if so, then we might as well just build it into MPF since so many games do this.

So that's where I was thinking if we just had a setting in multiball to drain all the balls, and then it could post a queue event when they were all drained, and when that queue is cleared, it can then serve a single ball back in play to the plunger lane.

I think this would only require adding a single setting (drain_all_on_stop: true) and would be pretty easy to implement? And if the game needed to play some show to summarize what just happened, they could hook the queue to do what they need and then when they release it, another ball is served.

We could make this automatically disable the flippers and autofire coils too since that's required to drain all the balls, and the MPF user could hook the MB stop event to disable anything else they wanted (lights, other devices, etc.)

**Comment by jabdoa2** [comment]
We got a eject_delay in ball_save: http://docs.missionpinball.org/en/latest/config/ball_saves.html#eject-delay. That will wait for all balls to drain first

**Comment by toomanybrians** [comment]
This can be done with the "only save last ball" option in the regular extra ball device.
