### ISSUE TITLE
Ignore entrance switch hits when releasing the first ball on full trough

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#844]
Currently a Gottlieb system11 trough might cause entrace_switch hits when releasing the first ball on a full trough. We should ignore this special case because the switch will just deactivate and might afterwards bounce on again.

**Comment by jabdoa2** [comment]
fixed in #847

**Comment by GabeKnuth** [comment]
Not entirely sure if this is related, but saw some strange trough behavior today while people were playing BnD. Biggest problem is that since I wasn't watching them I don't know all the details, but sometimes there were two ball in the trough, it kicked over one, then didn't act like there was another ball in the drain even though s_drain sat there closed. 

In the attached log file, the ball drained in ball 3, but the game / ball didn't end. 
[Archive 22.zip](https://github.com/missionpinball/mpf/files/884381/Archive.22.zip)

**Comment by GabeKnuth** [comment]
Saw your PR...didn't apply it earlier, so I'll do it when I get into the venue tomorrow morning. Thanks.
