### ISSUE TITLE
Error numbers and links to a description

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#922]
Use separate base classes (instead of AssertionError):
- ConfigFileError (errors caused by bad config settings)
- RuntimeError (errors at runtime)

Those exceptions take an error number and generate a link to our documentation when printed.

Where do we list the errors? How do we assign numbers?

**Comment by toomanybrians** [comment]
I love this idea!

A few random thoughts:

I like the idea of having all the errors online where we can have full details and links of how to resolve them. I also like having at least basic information in MPF/MPF-MC itself so it can locally provide an error number and short description. So I'm thinking the error numbers and short descriptions are in MPF (and MC, Monitor, etc.), and the full descriptions with links and troubleshooting are in mpf-docs?

It would be simple to add a script in mpf-docs that parses the error list from the various repos and creates the stub pages and/or updates descriptions if they change.

I like the idea of having the list of numbers and the short descriptions all in one file versus scattered throughout the code? Could be Python or YAML, but that way if we want a new error in code we just go to the `errors.yaml` and add another one to the bottom, and then raise that error number, and the error exception could handle the formatting for the log? So then in code we just do
`raise RuntimeError(123)` or something similar?

I also like the idea of having some sort of alpha prefix, like "mpe" for mpf and "mce" for MC.. or something like that? The reason is because back in my Microsoft days, since all theirs were "Q" followed by six digits, you could easily google [microsoft q123456] and get the result. And if we use a different prefix for MPF and MC then we can have separate lists for each and don't have to manage consecutive numbers across projects? Also those prefixes would be unique enough that someone could type [mpe123] into the docs search bar and they should find it. I'll make the page titles as SEO-friendly as possible, like "MPF Error mpe123: Not enough balls". That will also allow coders to simply create an error number and short description, and then I can write the full docs myself.

I think RTD supports forwarding of parts of URLs too, so I can make
`docs.missionpinball.org/error/mpe123` forward to `/en/latest/error/mpe123`

I think that's it for now? I am really excited about this!

**Comment by vgrillot** [comment]
Hi guys,

As a developper, it helps a lot to have a unique reference to identify an
error, obviously if you have a well documented page where you'll find how
to solve it :)
I'm use to check causes and solutions when working with Oracle with error
number, as "ORA-12345".

But whow, it sounds like a huge campain (pain?) to achive that !
Good luck with that !



Le mar. 9 mai 2017 à 17:44, Brian Madden <notifications@github.com> a
écrit :

**Comment by jabdoa2** [comment]
We got 197 AssertionErrors in MPF. I guess about 20%-50% would qualify for ConfigFileErrors. I'm not sure if I would want to remove the short description from the exception. More like this

`raise ConfigFileError(123, "Config setting abc: is invalid. Should be a, b or c.")`


Jan

**Comment by jabdoa2** [comment]
fixed in dev
